<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DataRowsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_rows')->delete();
        
        \DB::table('data_rows')->insert(array (
            0 => 
            array (
                'id' => 1,
                'data_type_id' => 1,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'data_type_id' => 1,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 2,
            ),
            2 => 
            array (
                'id' => 3,
                'data_type_id' => 1,
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'Email',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 3,
            ),
            3 => 
            array (
                'id' => 4,
                'data_type_id' => 1,
                'field' => 'password',
                'type' => 'password',
                'display_name' => 'Password',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"min":8,"max":50,"description":"min 8 characters."}',
                'order' => 4,
            ),
            4 => 
            array (
                'id' => 5,
                'data_type_id' => 1,
                'field' => 'remember_token',
                'type' => 'text',
                'display_name' => 'Remember Token',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            5 => 
            array (
                'id' => 6,
                'data_type_id' => 1,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            6 => 
            array (
                'id' => 7,
                'data_type_id' => 1,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            7 => 
            array (
                'id' => 8,
                'data_type_id' => 1,
                'field' => 'avatar',
                'type' => 'image',
                'display_name' => 'Avatar',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            8 => 
            array (
                'id' => 11,
                'data_type_id' => 1,
                'field' => 'settings',
                'type' => 'hidden',
                'display_name' => 'Settings',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 12,
            ),
            9 => 
            array (
                'id' => 12,
                'data_type_id' => 2,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            10 => 
            array (
                'id' => 13,
                'data_type_id' => 2,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            11 => 
            array (
                'id' => 14,
                'data_type_id' => 2,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 3,
            ),
            12 => 
            array (
                'id' => 15,
                'data_type_id' => 2,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            13 => 
            array (
                'id' => 16,
                'data_type_id' => 3,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            14 => 
            array (
                'id' => 17,
                'data_type_id' => 3,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 2,
            ),
            15 => 
            array (
                'id' => 18,
                'data_type_id' => 3,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 3,
            ),
            16 => 
            array (
                'id' => 19,
                'data_type_id' => 3,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 4,
            ),
            17 => 
            array (
                'id' => 20,
                'data_type_id' => 3,
                'field' => 'display_name',
                'type' => 'text',
                'display_name' => 'Display Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            18 => 
            array (
                'id' => 21,
                'data_type_id' => 1,
                'field' => 'role_id',
                'type' => 'text',
                'display_name' => 'Role',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            19 => 
            array (
                'id' => 22,
                'data_type_id' => 6,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            20 => 
            array (
                'id' => 23,
                'data_type_id' => 6,
                'field' => 'user_id',
                'type' => 'number',
                'display_name' => 'User Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 2,
            ),
            21 => 
            array (
                'id' => 24,
                'data_type_id' => 6,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 3,
            ),
            22 => 
            array (
                'id' => 25,
                'data_type_id' => 6,
                'field' => 'short_description',
                'type' => 'text',
                'display_name' => 'Short Description',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 4,
            ),
            23 => 
            array (
                'id' => 26,
                'data_type_id' => 6,
                'field' => 'description',
                'type' => 'text',
                'display_name' => 'Description',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            24 => 
            array (
                'id' => 27,
                'data_type_id' => 6,
                'field' => 'goal',
                'type' => 'number',
                'display_name' => 'Goal',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            25 => 
            array (
                'id' => 28,
                'data_type_id' => 6,
                'field' => 'starts_at',
                'type' => 'date',
                'display_name' => 'Starts At',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            26 => 
            array (
                'id' => 29,
                'data_type_id' => 6,
                'field' => 'ends_at',
                'type' => 'date',
                'display_name' => 'Ends At',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            27 => 
            array (
                'id' => 30,
                'data_type_id' => 6,
                'field' => 'fundraising',
                'type' => 'select_dropdown',
                'display_name' => 'Fundraising',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"default":"active","options":{"active":"active","inactive":"inactive"}}',
                'order' => 9,
            ),
            28 => 
            array (
                'id' => 31,
                'data_type_id' => 6,
                'field' => 'status',
                'type' => 'select_dropdown',
                'display_name' => 'Status',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"default":"published","options":{"published":"published","unpublished":"unpublished"}}',
                'order' => 10,
            ),
            29 => 
            array (
                'id' => 32,
                'data_type_id' => 6,
                'field' => 'fundraising_after_goal',
                'type' => 'select_dropdown',
                'display_name' => 'Fundraising After Goal',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"default":"active","options":{"active":"active","inactive":"inactive"}}',
                'order' => 11,
            ),
            30 => 
            array (
                'id' => 33,
                'data_type_id' => 6,
                'field' => 'fundraising_after_date',
                'type' => 'select_dropdown',
                'display_name' => 'Fundraising After Date',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"default":"active","options":{"active":"active","inactive":"inactive"}}',
                'order' => 12,
            ),
            31 => 
            array (
                'id' => 34,
                'data_type_id' => 6,
                'field' => 'status_after_date',
                'type' => 'select_dropdown',
                'display_name' => 'Status After Date',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"default":"published","options":{"published":"published","unpublished":"unpublished"}}',
                'order' => 13,
            ),
            32 => 
            array (
                'id' => 35,
                'data_type_id' => 6,
                'field' => 'token',
                'type' => 'text',
                'display_name' => 'Token',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 21,
            ),
            33 => 
            array (
                'id' => 36,
                'data_type_id' => 6,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 22,
            ),
            34 => 
            array (
                'id' => 37,
                'data_type_id' => 6,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 23,
            ),
            35 => 
            array (
                'id' => 38,
                'data_type_id' => 6,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 24,
            ),
            36 => 
            array (
                'id' => 39,
                'data_type_id' => 7,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            37 => 
            array (
                'id' => 40,
                'data_type_id' => 7,
                'field' => 'campaign_id',
                'type' => 'number',
                'display_name' => 'Campaign Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 2,
            ),
            38 => 
            array (
                'id' => 41,
                'data_type_id' => 7,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 3,
            ),
            39 => 
            array (
                'id' => 42,
                'data_type_id' => 7,
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'Email',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 4,
            ),
            40 => 
            array (
                'id' => 43,
                'data_type_id' => 7,
                'field' => 'phone',
                'type' => 'number',
                'display_name' => 'Phone',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            41 => 
            array (
                'id' => 44,
                'data_type_id' => 7,
                'field' => 'cpf',
                'type' => 'CPF',
                'display_name' => 'Cpf',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            42 => 
            array (
                'id' => 45,
                'data_type_id' => 7,
                'field' => 'rsvp',
                'type' => 'select_dropdown',
                'display_name' => 'Rsvp',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"default":"no","options":{"0":"no","1":"yes"}}',
                'order' => 7,
            ),
            43 => 
            array (
                'id' => 46,
                'data_type_id' => 7,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            44 => 
            array (
                'id' => 47,
                'data_type_id' => 7,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            45 => 
            array (
                'id' => 48,
                'data_type_id' => 7,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 10,
            ),
            46 => 
            array (
                'id' => 49,
                'data_type_id' => 8,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            47 => 
            array (
                'id' => 50,
                'data_type_id' => 8,
                'field' => 'campaign_id',
                'type' => 'number',
                'display_name' => 'Campaign Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 2,
            ),
            48 => 
            array (
                'id' => 51,
                'data_type_id' => 8,
                'field' => 'invitee_id',
                'type' => 'number',
                'display_name' => 'Invitee Id',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 3,
            ),
            49 => 
            array (
                'id' => 52,
                'data_type_id' => 8,
                'field' => 'amount',
                'type' => 'number',
                'display_name' => 'Amount',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 4,
            ),
            50 => 
            array (
                'id' => 53,
                'data_type_id' => 8,
                'field' => 'transaction_id',
                'type' => 'text',
                'display_name' => 'Transaction Id',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            51 => 
            array (
                'id' => 54,
                'data_type_id' => 8,
                'field' => 'pdf',
                'type' => 'text',
                'display_name' => 'Pdf',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            52 => 
            array (
                'id' => 55,
                'data_type_id' => 8,
                'field' => 'status',
                'type' => 'select_dropdown',
                'display_name' => 'Status',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"default":"created","options":{"created":"created","paid":"paid","credited":"credited"}}',
                'order' => 7,
            ),
            53 => 
            array (
                'id' => 56,
                'data_type_id' => 8,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 10,
            ),
            54 => 
            array (
                'id' => 57,
                'data_type_id' => 8,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 11,
            ),
            55 => 
            array (
                'id' => 72,
                'data_type_id' => 1,
                'field' => 'email_verified_at',
                'type' => 'timestamp',
                'display_name' => 'Email Verified At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            56 => 
            array (
                'id' => 73,
                'data_type_id' => 1,
                'field' => 'two_factor_secret',
                'type' => 'text',
                'display_name' => 'Two Factor Secret',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            57 => 
            array (
                'id' => 74,
                'data_type_id' => 1,
                'field' => 'two_factor_recovery_codes',
                'type' => 'text',
                'display_name' => 'Two Factor Recovery Codes',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            58 => 
            array (
                'id' => 75,
                'data_type_id' => 1,
                'field' => 'two_factor_confirmed_at',
                'type' => 'timestamp',
                'display_name' => 'Two Factor Confirmed At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 10,
            ),
            59 => 
            array (
                'id' => 76,
                'data_type_id' => 1,
                'field' => 'current_team_id',
                'type' => 'text',
                'display_name' => 'Current Team Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 13,
            ),
            60 => 
            array (
                'id' => 77,
                'data_type_id' => 1,
                'field' => 'profile_photo_path',
                'type' => 'text',
                'display_name' => 'Profile Photo Path',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 14,
            ),
            61 => 
            array (
                'id' => 78,
                'data_type_id' => 6,
                'field' => 'campaign_hasmany_invitee_relationship',
                'type' => 'relationship',
                'display_name' => 'invitees',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"model":"App\\\\Models\\\\Invitee","table":"invitees","type":"hasMany","column":"campaign_id","key":"id","label":"invitees","pivot_table":"admins","pivot":"0","taggable":"0"}',
                'order' => 16,
            ),
            62 => 
            array (
                'id' => 89,
                'data_type_id' => 6,
                'field' => 'campaign_hasmany_pix_payment_relationship',
                'type' => 'relationship',
                'display_name' => 'pix_payments',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"model":"App\\\\Models\\\\PixPayment","table":"pix_payments","type":"hasMany","column":"campaign_id","key":"id","label":"pixpayments","pivot_table":"admins","pivot":"0","taggable":"0"}',
                'order' => 17,
            ),
            63 => 
            array (
                'id' => 90,
                'data_type_id' => 6,
                'field' => 'campaign_hasmany_institution_relationship',
                'type' => 'relationship',
                'display_name' => 'Institution',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"description":"defina uma institui\\u00e7\\u00e3o para fazer a doa\\u00e7\\u00e3o.","model":"App\\\\Models\\\\Institution","table":"institutions","type":"belongsTo","column":"institution_id","key":"id","label":"name","pivot_table":"admins","pivot":"0","taggable":"0"}',
                'order' => 20,
            ),
            64 => 
            array (
                'id' => 93,
                'data_type_id' => 14,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            65 => 
            array (
                'id' => 94,
                'data_type_id' => 14,
                'field' => 'campaign_id',
                'type' => 'number',
                'display_name' => 'Campaign Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 2,
            ),
            66 => 
            array (
                'id' => 95,
                'data_type_id' => 14,
                'field' => 'type',
                'type' => 'select_dropdown',
                'display_name' => 'Type',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"default":"host_payout","options":{"host_payout":"host_payout","charity_payout":"charity_payout"}}',
                'order' => 3,
            ),
            67 => 
            array (
                'id' => 96,
                'data_type_id' => 14,
                'field' => 'amount',
                'type' => 'Currency',
                'display_name' => 'Amount',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"description":"valor em Reais R$."}',
                'order' => 4,
            ),
            68 => 
            array (
                'id' => 97,
                'data_type_id' => 14,
                'field' => 'attachment',
                'type' => 'image',
                'display_name' => 'Attachment',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"resize":{"width":"700","height":null},"quality":"70%","upsize":true,"thumbnails":[{"name":"medium","scale":"50%"},{"name":"small","scale":"25%"},{"name":"cropped","crop":{"width":"300","height":null}}]}',
                'order' => 5,
            ),
            69 => 
            array (
                'id' => 98,
                'data_type_id' => 14,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            70 => 
            array (
                'id' => 99,
                'data_type_id' => 14,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            71 => 
            array (
                'id' => 100,
                'data_type_id' => 14,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            72 => 
            array (
                'id' => 102,
                'data_type_id' => 6,
                'field' => 'campaign_hasmany_campaign_payout_relationship',
                'type' => 'relationship',
                'display_name' => 'campaign_payouts',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"model":"App\\\\Models\\\\CampaignPayout","table":"campaign_payouts","type":"hasMany","column":"campaign_id","key":"id","label":"campaignpayouts","pivot_table":"admins","pivot":"0","taggable":"0"}',
                'order' => 18,
            ),
            73 => 
            array (
                'id' => 103,
                'data_type_id' => 19,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            74 => 
            array (
                'id' => 104,
                'data_type_id' => 19,
                'field' => 'campaign_id',
                'type' => 'number',
                'display_name' => 'Campaign Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 2,
            ),
            75 => 
            array (
                'id' => 105,
                'data_type_id' => 19,
                'field' => 'type',
                'type' => 'select_dropdown',
                'display_name' => 'Type',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"default":"image","options":{"image":"image"}}',
                'order' => 3,
            ),
            76 => 
            array (
                'id' => 106,
                'data_type_id' => 19,
                'field' => 'uri',
                'type' => 'image',
                'display_name' => 'logo',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"resize":{"width":"700","height":null},"quality":"70%","upsize":true,"thumbnails":[{"name":"medium","scale":"50%"},{"name":"small","scale":"25%"},{"name":"cropped","crop":{"width":"300","height":null}}]}',
                'order' => 4,
            ),
            77 => 
            array (
                'id' => 107,
                'data_type_id' => 19,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            78 => 
            array (
                'id' => 108,
                'data_type_id' => 19,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            79 => 
            array (
                'id' => 109,
                'data_type_id' => 19,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            80 => 
            array (
                'id' => 110,
                'data_type_id' => 6,
                'field' => 'campaign_hasmany_campaign_media_relationship',
                'type' => 'relationship',
                'display_name' => 'Campaign medias',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"model":"App\\\\Models\\\\CampaignMedia","table":"campaign_medias","type":"hasMany","column":"campaign_id","key":"id","label":"campaign_medias","pivot_table":"admins","pivot":"0","taggable":"0"}',
                'order' => 19,
            ),
            81 => 
            array (
                'id' => 111,
                'data_type_id' => 20,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            82 => 
            array (
                'id' => 112,
                'data_type_id' => 20,
                'field' => 'role_id',
                'type' => 'select_dropdown',
                'display_name' => 'Role',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"options":{"1":"admin","2":"user","3":"admin user"}}',
                'order' => 2,
            ),
            83 => 
            array (
                'id' => 113,
                'data_type_id' => 20,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 3,
            ),
            84 => 
            array (
                'id' => 114,
                'data_type_id' => 20,
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'Email',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 4,
            ),
            85 => 
            array (
                'id' => 115,
                'data_type_id' => 20,
                'field' => 'avatar',
                'type' => 'image',
                'display_name' => 'Avatar',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"resize":{"width":"300","height":null},"quality":"70%","upsize":true,"thumbnails":[{"name":"medium","scale":"50%"},{"name":"small","scale":"25%"},{"name":"cropped","crop":{"width":"300","height":null}}]}',
                'order' => 5,
            ),
            86 => 
            array (
                'id' => 116,
                'data_type_id' => 20,
                'field' => 'password',
                'type' => 'text',
                'display_name' => 'Password',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            87 => 
            array (
                'id' => 117,
                'data_type_id' => 20,
                'field' => 'remember_token',
                'type' => 'text',
                'display_name' => 'Remember Token',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            88 => 
            array (
                'id' => 118,
                'data_type_id' => 20,
                'field' => 'settings',
                'type' => 'text',
                'display_name' => 'Settings',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            89 => 
            array (
                'id' => 119,
                'data_type_id' => 20,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            90 => 
            array (
                'id' => 120,
                'data_type_id' => 20,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 10,
            ),
            91 => 
            array (
                'id' => 130,
                'data_type_id' => 8,
                'field' => 'brcode',
                'type' => 'text',
                'display_name' => 'Brcode',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            92 => 
            array (
                'id' => 131,
                'data_type_id' => 8,
                'field' => 'link',
                'type' => 'text',
                'display_name' => 'Link',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            93 => 
            array (
                'id' => 143,
                'data_type_id' => 6,
                'field' => 'institution_id',
                'type' => 'number',
                'display_name' => 'Institution Id',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 14,
            ),
            94 => 
            array (
                'id' => 144,
                'data_type_id' => 6,
                'field' => 'tax_charity',
                'type' => 'number',
                'display_name' => 'Tax Charity',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"step":0.1,"min":0,"max":100,"default":0,"description":"defina um valor entre 0 e 100% para fazer a doa\\u00e7\\u00e3o."}',
                'order' => 15,
            ),
            95 => 
            array (
                'id' => 146,
                'data_type_id' => 14,
                'field' => 'institution_id',
                'type' => 'text',
                'display_name' => 'Institution Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            96 => 
            array (
                'id' => 147,
                'data_type_id' => 21,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            97 => 
            array (
                'id' => 148,
                'data_type_id' => 21,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 2,
            ),
            98 => 
            array (
                'id' => 149,
                'data_type_id' => 21,
                'field' => 'cnpj',
                'type' => 'text',
                'display_name' => 'Cnpj',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 3,
            ),
            99 => 
            array (
                'id' => 150,
                'data_type_id' => 21,
                'field' => 'description',
                'type' => 'text',
                'display_name' => 'Description',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 4,
            ),
            100 => 
            array (
                'id' => 151,
                'data_type_id' => 21,
                'field' => 'logo',
                'type' => 'image',
                'display_name' => 'Logo',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            101 => 
            array (
                'id' => 152,
                'data_type_id' => 21,
                'field' => 'bank_name',
                'type' => 'text',
                'display_name' => 'Bank Name',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            102 => 
            array (
                'id' => 153,
                'data_type_id' => 21,
                'field' => 'bank_code',
                'type' => 'text',
                'display_name' => 'Bank Code',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            103 => 
            array (
                'id' => 154,
                'data_type_id' => 21,
                'field' => 'bank_agency',
                'type' => 'number',
                'display_name' => 'Bank Agency',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            104 => 
            array (
                'id' => 155,
                'data_type_id' => 21,
                'field' => 'bank_account_number',
                'type' => 'number',
                'display_name' => 'Bank Account Number',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            105 => 
            array (
                'id' => 156,
                'data_type_id' => 21,
                'field' => 'bank_pix_key',
                'type' => 'text',
                'display_name' => 'Bank Pix Key',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 10,
            ),
            106 => 
            array (
                'id' => 157,
                'data_type_id' => 21,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 11,
            ),
            107 => 
            array (
                'id' => 158,
                'data_type_id' => 21,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 12,
            ),
            108 => 
            array (
                'id' => 159,
                'data_type_id' => 21,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 13,
            ),
            109 => 
            array (
                'id' => 160,
                'data_type_id' => 6,
                'field' => 'type',
                'type' => 'text',
                'display_name' => 'Type',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 7,
            ),
            110 => 
            array (
                'id' => 161,
                'data_type_id' => 6,
                'field' => 'address',
                'type' => 'text',
                'display_name' => 'Address',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 8,
            ),
            111 => 
            array (
                'id' => 162,
                'data_type_id' => 6,
                'field' => 'date_rsvp',
                'type' => 'text',
                'display_name' => 'Date Rsvp',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 9,
            ),
            112 => 
            array (
                'id' => 163,
                'data_type_id' => 6,
                'field' => 'receive_gifts',
                'type' => 'text',
                'display_name' => 'Receive Gifts',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 14,
            ),
            113 => 
            array (
                'id' => 164,
                'data_type_id' => 6,
                'field' => 'donate_to_charity',
                'type' => 'text',
                'display_name' => 'Donate To Charity',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 15,
            ),
            114 => 
            array (
                'id' => 173,
                'data_type_id' => 28,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            115 => 
            array (
                'id' => 174,
                'data_type_id' => 28,
                'field' => 'url',
                'type' => 'text',
                'display_name' => 'Url',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            116 => 
            array (
                'id' => 175,
                'data_type_id' => 28,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 3,
            ),
            117 => 
            array (
                'id' => 176,
                'data_type_id' => 28,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 4,
            ),
            118 => 
            array (
                'id' => 177,
                'data_type_id' => 28,
                'field' => 'webhook_id',
                'type' => 'text',
                'display_name' => 'Webhook Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 2,
            ),
            119 => 
            array (
                'id' => 178,
                'data_type_id' => 28,
                'field' => 'status',
                'type' => 'text',
                'display_name' => 'Status',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 4,
            ),
        ));
        
        
    }
}